version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000" # Assurez-vous que le port externe est 5000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/EFREI_Projet
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: