name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        cd ../backend
        npm ci
    - name: Run frontend tests
      run: |
        cd frontend
        npm test
    - name: Run backend tests
      run: |
        cd backend
        npm test